full Laravel task
pelmenos/LearnLaravel pull request #1
Opened 2023-11-14 07:38 UTC by pelmenos

Задание по ларавелю.
Для аутентификации по токенам я использовал sanctum, для прав доступа я создал таблицу Permission, и через неё выдавал права для файлов. Проверку прав на владельца и автора сделал через мидлвари. Это все основные моменты

2023-11-14 13:00 UTC, RetmixX requested changes
Поправь замечания и почитай эти статьи:
https://laravel.com/docs/10.x/controllers#resource-controllers
https://laravel.com/docs/10.x/routing#route-model-binding
ВЫНЕСТИ ЛОГИКУ ИЗ КОНТРОЛЛЕРОВ

2023-11-14 13:00 UTC, RetmixX commented on app/Http/Controllers/Api/FileController.php
> +        $request->validate([
https://laravel.com/docs/10.x/validation#form-request-validation

2023-11-14 13:00 UTC, RetmixX commented on app/Http/Controllers/Api/PermissionController.php
Типизация на методах + есть класс JsonResponse

2023-11-15 03:28 UTC, jurapro requested changes
- [ ] в начале сделали комментарии, по всему коду ошибки однотипные, нужно порефачить
- [ ] общие ошибки на встрече скажу

2023-11-15 03:28 UTC, jurapro commented on app/Exceptions/Handler.php
> +                return response()->json([
В отдельные классы вынеси

2023-11-15 03:28 UTC, jurapro commented on app/Http/Controllers/Api/FileController.php
> +        while (in_array($name, $dir)){
нужно отрефачить есть методы collection https://laravel.com/docs/10.x/collections

2023-11-15 03:28 UTC, jurapro commented on app/Http/Controllers/Api/FileController.php
> +            try {
перехват исключения вынести в handler

2023-11-15 03:28 UTC, jurapro commented on app/Http/Controllers/Api/FileController.php
> +        return response()->json($response);
Используем resourse https://laravel.com/docs/10.x/eloquent-resources

2023-11-15 03:28 UTC, jurapro commented on app/Http/Controllers/Api/FileController.php
> +        unlink($this->getFilePath($file->name));
Используем методы ларавель работы с файлами

2023-11-15 03:28 UTC, jurapro commented on app/Http/Controllers/Api/UserController.php
> +        $response['token'] = $user->createToken('MyApp')->plainTextToken;
зараз можно задать

2023-11-15 03:28 UTC, jurapro commented on app/Http/Middleware/IsAuthor.php
> +class IsAuthor
обычно мидлвары используются для более крупных проверок (авторизирован ли, администратор ли и пр.) Для проверки на авторство используются другие механизмы типа политик https://laravel.com/docs/10.x/authorization#creating-policies

2023-11-15 03:28 UTC, jurapro commented on app/Http/Middleware/RedirectIfAuthenticated.php
> +        $guards = empty($guards) ? [null] : $guards;
можно короче

2023-11-15 03:28 UTC, jurapro commented on app/Models/Permission.php
> +    public static function createCoAuthor(int $user_id, int $file_id): void
это сюда не выносится обчно

2023-11-16 06:08 UTC, jurapro approved these changes
мелкие замечания

2023-11-16 06:08 UTC, jurapro commented on app/Http/Controllers/Api/FileController.php
> +        return collect($files)->map(function($file){
валидацию вынести в StoreFileRequest
вывод данных вывести в ресурсы

2023-11-16 06:08 UTC, jurapro commented on app/Http/Resources/FileResource.php
> +            'url' => $_SERVER['HTTP_HOST'] . '/files/' . $this->file_id
$_SERVER['HTTP_HOST'] . '/files/' . - вместо этого алиас ларавеля

2023-11-17 08:37 UTC, pelmenos commented on app/Http/Controllers/Api/FileController.php
> +        return collect($files)->map(function($file){
Я думаю эта валидация и должна остаться. Дело же в том, что какие-то файлы могут иметь нужное расширение, а какие-то нет. В задании сказано, что если такое происходит, то нужно не возвращать ошибку, а просто возвращать массив с загруженными и не загруженными файлами

2023-11-17 11:01 UTC, pelmenos reviewed
Тут я немного разобрался как работать с manytomany в ларавеле из-за этого контроллеры уменьшились раза в два. Потом получение файлов пользователя  и доступ пользователя к файлам вынес в FileController, не знаю почему я это написал в PermissionController.

2023-11-19 13:23 UTC, jurapro approved these changes

2023-11-26 08:29 UTC, merged